feat(value-node): update method, serialised and parent getters
editor-js/document-model pull request #7
Opened 2023-05-29 13:58 UTC by ilyamore88

Added ValueNode methods and getters with unit tests.

2023-05-29 14:07 UTC, neSpecc commented on src/entities/ValueNode/ValueNode.spec.ts
> +    it('should add new data field associated with this value node', () => {
Are you sure that we need to allow adding new properties to ValueNode? 

Seems like ValueNode should only allow updating of existed value which was set through the Constructor. And disallow adding new properties later

2023-05-30 19:32 UTC, gohabereg requested changes

2023-05-30 19:32 UTC, gohabereg commented on src/entities/BlockNode/types/BlockNodeChildren.ts
> +export type BlockNodeChildren = Record<DataKey, ValueNode[] | (FormattingNode | TextNode)[]>;
Why array?

2023-05-30 19:32 UTC, gohabereg commented on src/entities/ValueNode/ValueNode.spec.ts
> +        name: createValueNodeName('longitude'),
I don't think node itself needs to know it's DataKey

2023-05-30 19:32 UTC, gohabereg commented on src/entities/ValueNode/index.ts
> +      name: this.#name,
It should return just value

2023-05-30 19:32 UTC, gohabereg commented on src/entities/ValueNode/ValueNode.spec.ts
> +        name: createValueNodeName('longitude'),
Not sure about a parent as well though

2023-05-30 19:51 UTC, gohabereg commented on src/utils/mocks/createValueNodeMock.ts
> +export function createValueNodeMock({ value }: { value: unknown }): ValueNode {
You can use ConstructorParameters interface here

2023-05-30 19:55 UTC, neSpecc approved these changes
ok

2023-05-30 19:57 UTC, gohabereg approved these changes

2023-05-30 19:59 UTC, merged